@ECHO ON
SETLOCAL ENABLEDELAYEDEXPANSION
SET RIMWORLD_MOD_DEBUG=--debugger-agent=transport=dt_socket,address=127.0.0.1:56000,server=y
SET SOLUTION_DIR=%~2
SET PROJECT_DIR=%~7
SET RIMWORLD_DIR_STANDALONE2=C:\Users\cwc02\RimWorldDebug
SET TARGET_DIR=%RIMWORLD_DIR_STEAM%\Mods\PRF_Core
SET TARGET_DEBUG_DIR=%RIMWORLD_DIR_STANDALONE2%\Mods\PRF_Core
SET ZIP_EXE="C:\Program Files\7-Zip\7z.exe"
SET OUTPUT_PATH=%~2
SET OUTPUT_PATH=%SOLUTION_DIR:~0,-7%PRF_Core\Assemblies
SET OUTPUTMOD_PATH=%SOLUTION_DIR:~0,-7%PRF_Core\
SET HARMONY_PATH=%PROJECT_DIR%bin\Debug\0Harmony.dll
SET MOD_DLL_PATH=%PROJECT_DIR%bin\Debug\%~3.dll

IF %1==Debug (
	IF EXIST "%HARMONY_PATH:~0,-4%.pdb" (
		ECHO "Creating mdb at %HARMONY_PATH%"
		"%MONO_EXE%" "%PDB2MDB_PATH%" "%HARMONY_PATH%" 1>NUL
	)
	ECHO "Copying to %OUTPUT_PATH%"
	FOR %%D IN (%~5) DO (
		XCOPY /I /Y /E "%PROJECT_DIR%%~6%%D" "%OUTPUT_PATH%\%%D" 1>NUL
	)
	IF EXIST "%MOD_DLL_PATH:~0,-4%.pdb" (
		ECHO "Creating mdb at %MOD_DLL_PATH%"
		"%MONO_EXE%" "%PDB2MDB_PATH%" "%MOD_DLL_PATH%" 1>NUL
	)
)

IF %1==Release (
	IF EXIST "%HARMONY_PATH%.mdb" (
		ECHO "Deleting %HARMONY_PATH%.mdb"
		DEL "%HARMONY_PATH%.mdb" 1>NUL
	)
	IF EXIST "%MOD_DLL_PATH%.mdb" (
		ECHO "Deleting %MOD_DLL_PATH%.mdb"
		DEL "%MOD_DLL_PATH%.mdb" 1>NUL
	)
)

IF EXIST "%RIMWORLD_DIR_STANDALONE2%" (
	ECHO "Copying to %TARGET_DEBUG_DIR%"
	IF NOT EXIST "%TARGET_DEBUG_DIR%" MKDIR "%TARGET_DEBUG_DIR%" 1>NUL
	FOR %%D IN (%~4) DO (
		XCOPY /I /Y /E "%OUTPUTMOD_PATH%%%D" "%TARGET_DEBUG_DIR%\%%D" 1>NUL
	)
		FOR %%D IN (%~8) DO (
		XCOPY /I /Y /E "%PROJECT_DIR%%~6%%D" "%TARGET_DEBUG_DIR%\Assemblies\%%D" 1>NUL
	)
)

IF EXIST "%RIMWORLD_DIR_STEAM%" (
	ECHO "Copying to %TARGET_DIR%"
	IF NOT EXIST "%TARGET_DIR%" MKDIR "%TARGET_DIR%"
	FOR %%D IN (%~4) DO (
		XCOPY /I /Y /E "%OUTPUTMOD_PATH%%%D" "%TARGET_DIR%\%%D" 1>NUL
	)
	%ZIP_EXE% a "%TARGET_DIR%.zip" "%TARGET_DIR%" 1>NUL
)